site_name: Managed Aleph
site_url: https://investigativedata.io/aleph
nav:
  - Overview: index.md
  - features.md
  - faq.md
  - why-us.md
  - credits.md
  - Legal:
    - TOS: legal/tos.md
    - SLA: legal/sla.md
  - Contact:
    - › Email us: mailto:hi@investigativedata.org
    - › investigativedata.io: https://investigativedata.io
    - leak-to-us.md
  - External resources:
    - › Aleph user documentation: https://docs.alephdata.org
    - › Explore Aleph: https://aleph.investigativedata.org
    - › Aleph on github: https://github.com/alephdata
theme:
  name: material
  custom_dir: overrides
  logo: https://cdn.investigativedata.org/style/logo_basic_dark.svg
  favicon: https://cdn.investigativedata.org/style/favicon.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - navigation.footer
    - toc.follow
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  social:
    - icon: material/web
      link: https://investigativedata.io
    - icon: material/mail
      link: mailto:hi@investigativedata.org
    - icon: material/github
      link: https://github.com/investigativedata
