name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  preview:
    environment:
      name: preview
      url: https://dev.investigativedata.io/${{ GITHUB_SHA }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*'
        env:
          AWS_S3_BUCKET: cdn.investigativedata.org
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_REGION: "eu-central-1"
          DEST_DIR: ${{ GITHUB_SHA }}
